/**
 * Type definitions for contradictions in research evidence
 * @ai-context VERY IMPORTANT - Contradictions must be prominently displayed
 */

/**
 * Severity of contradiction
 */
export enum ContradictionSeverity {
  MINOR = 'minor',   // Small differences, likely methodological
  MAJOR = 'major',   // Significant conflict requiring attention
}

/**
 * Status of contradiction resolution
 */
export enum ContradictionStatus {
  UNRESOLVED = 'unresolved', // Conflict not yet explained
  EXPLAINED = 'explained',   // Methodological differences identified
  ONGOING = 'ongoing',       // Active debate in research community
}

/**
 * View representing one side of a contradiction
 */
export interface ContradictionView {
  description: string; // What this view claims
  papers: string[]; // Paper IDs supporting this view
  evidence: string; // Specific evidence/data
  paperCount: number; // Number of supporting papers
}

/**
 * Contradiction between research findings
 * CRITICAL: These must be displayed with prominent yellow warning
 */
export interface Contradiction {
  // Identity
  id: string; // UUID v4
  findingId: string; // Parent finding ID
  topic: string; // What the contradiction is about

  // The conflict
  majorityView: ContradictionView; // View with more papers
  minorityView: ContradictionView; // View with fewer papers

  // Analysis
  methodologicalDifferences: string[]; // Why papers might disagree
  possibleExplanations: string[]; // Biological explanations
  severity: ContradictionSeverity; // How serious is this conflict

  // Resolution
  status: ContradictionStatus; // Resolution status
  conservativeInterpretation: string; // What we can safely conclude

  // Metadata
  dateDetected: string; // ISO 8601 timestamp
  lastUpdated: string; // ISO 8601 timestamp

  // User data
  userAnalysis?: string; // User's own interpretation
  flaggedForResearch: boolean; // User wants to investigate further
}

/**
 * Analysis of why papers contradict
 * Generated by ContradictionDetector tool
 */
export interface DiscrepancyAnalysis {
  methodologicalDifferences: string[]; // Method differences
  sampleSizeComparison: string; // Sample size comparison
  qualityComparison: string; // Study quality comparison
  timingDifferences: string[]; // Timing/temporal differences
  populationDifferences: string[]; // Patient population differences
  possibleBiologicalExplanations: string[]; // Why both might be true
}

/**
 * Type guard to check if a value is a valid ContradictionSeverity
 */
export const isContradictionSeverity = (
  value: string
): value is ContradictionSeverity => {
  return Object.values(ContradictionSeverity).includes(
    value as ContradictionSeverity
  );
};

/**
 * Type guard to check if a value is a valid ContradictionStatus
 */
export const isContradictionStatus = (
  value: string
): value is ContradictionStatus => {
  return Object.values(ContradictionStatus).includes(
    value as ContradictionStatus
  );
};

/**
 * Factory function to create a new contradiction
 */
export const createContradiction = (
  findingId: string,
  topic: string,
  majorityView: ContradictionView,
  minorityView: ContradictionView
): Contradiction => {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    findingId,
    topic,
    majorityView,
    minorityView,
    methodologicalDifferences: [],
    possibleExplanations: [],
    severity: ContradictionSeverity.MAJOR,
    status: ContradictionStatus.UNRESOLVED,
    conservativeInterpretation: '',
    dateDetected: now,
    lastUpdated: now,
    flaggedForResearch: true,
  };
};

