/**
 * Type definitions for research questions and evidence synthesis
 * @ai-context Phase 2 data model for Q&A system with conservative evidence presentation
 */

import type { Finding } from './finding';
import type { Contradiction } from './contradiction';
import type { Note } from './database';

/**
 * Version snapshot of a research question
 * Tracks historical states for comparison
 */
export interface QuestionVersion {
  id: string; // UUID for this version
  versionNumber: number; // 1, 2, 3...
  dateGenerated: string; // ISO 8601 timestamp
  findings: Finding[]; // Findings at this version
  contradictions: Contradiction[];
  paperCount: number;
  confidence: number;
  status: QuestionStatus;
  papersUsed: string[]; // Paper IDs that contributed
}

/**
 * Status of research question based on available evidence
 */
export enum QuestionStatus {
  UNANSWERED = 'unanswered',  // No papers address this yet
  PARTIAL = 'partial',         // Some evidence exists, but gaps remain
  ANSWERED = 'answered',       // Sufficient evidence to answer
}

/**
 * Research question with evidence synthesis
 * Core entity for organizing knowledge around user questions
 */
export interface ResearchQuestion {
  // Identity
  id: string; // UUID v4
  question: string; // User's research question

  // Status
  status: QuestionStatus;
  confidence: number; // 0-1 confidence in current answer

  // Evidence
  findings: Finding[]; // Evidence extracted from papers
  contradictions: Contradiction[]; // Detected conflicts in evidence
  gaps: string[]; // What we don't know yet

  // Metadata
  dateCreated: string; // ISO 8601 timestamp
  lastUpdated: string; // ISO 8601 timestamp
  paperCount: number; // Number of papers addressing this

  // User organization
  isPriority: boolean; // User-marked priority
  userNotes: Note[]; // User annotations
  relatedQuestions: string[]; // IDs of related questions

  // Version history
  currentVersion: number; // Current version number (starts at 1)
  versions: QuestionVersion[]; // Full history (keep all)
  orphanedNotes?: Array<[string, string]>; // [findingText, note] - notes from removed findings
  papersUsed: string[]; // Paper IDs used in current version
}

/**
 * Evidence synthesis result for a question
 * Generated by EvidenceExtractor tool
 */
export interface EvidenceSynthesis {
  summary: string; // Overall conservative answer
  findings: FindingSummary[]; // Grouped findings
  confidence: number; // 0-1 overall confidence
  limitations: string[]; // Study limitations
  gaps: string[]; // Knowledge gaps
}

/**
 * Summary of grouped findings
 */
export interface FindingSummary {
  description: string; // What was found
  paperCount: number; // Number of supporting papers
  papers: string[]; // Paper IDs
  consistency: 'high' | 'medium' | 'low'; // Agreement across papers
  evidence: string; // Specific evidence/data
  limitations: string[]; // Study limitations
}

/**
 * Type guard to check if a value is a valid QuestionStatus
 */
export const isQuestionStatus = (value: string): value is QuestionStatus => {
  return Object.values(QuestionStatus).includes(value as QuestionStatus);
};

/**
 * Factory function to create a new research question
 */
export const createResearchQuestion = (
  question: string
): ResearchQuestion => {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    question,
    status: QuestionStatus.UNANSWERED,
    confidence: 0,
    findings: [],
    contradictions: [],
    gaps: [],
    dateCreated: now,
    lastUpdated: now,
    paperCount: 0,
    isPriority: false,
    userNotes: [],
    relatedQuestions: [],
    currentVersion: 1,
    versions: [],
    orphanedNotes: [],
    papersUsed: [],
  };
};

